<?php

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

global $icons_inverted_array;

// Counter
vc_map(
	array(
		'name' => __( 'Counter', 'tattoopro' ),
		'base' => 'wolf_counter',
		'category' => 'by WolfThemes',
		'icon' => 'wolf-vc-icon wolf-vc-counter',
		'allowed_container_element' => 'vc_row',
		'params' => array(

			array(
				'type' => 'textfield',
				'admin_label' => true,
				'class' => '',
				'heading' => __( 'Number', 'tattoopro' ),
				'param_name' => 'number',
				'description' => __( 'It can be a shortcode that generate a number in this case paste your shortcode without the []', 'tattoopro' ),
				'value' => '',
			),

			array(
				'type' => 'checkbox',
				'class' => '',
				'show_settings_on_create' => true,
				'heading' => '',
				'param_name' => 'shortcode',
				'value' => array( __( 'Is your number generated by a shortcode?', 'tattoopro' ) => true ),
			),
			array(
				'type' => 'textfield',
				'admin_label' => true,
				'class' => '',
				'heading' => __( 'Text', 'tattoopro' ),
				'param_name' => 'text',
				'description' => '',
				'value' => '',
			),

			array(
				'type' => 'dropdown',
				'class' => '',
				'heading' => __( 'Add icon', 'tattoopro' ),
				'param_name' => 'add_icon',
				'value' => array(
					__( 'No', 'tattoopro' ) => 'no',
					__( 'Yes', 'tattoopro' ) => 'yes'
				),
			),

			array(
				'type' => 'searchable',
				'admin_label' => true,
				'class' => '',
				'heading' => __( 'Icon', 'tattoopro' ),
				'param_name' => 'icon',
				'value' => $icons_inverted_array,
				'description' => '',
				'dependency' => array( 'element' => 'add_icon', 'value' => array( 'yes' ) ),
			),

			array(
				'type' => 'textfield',
				'admin_label' => true,
				'class' => '',
				'heading' => __( 'Inline style', 'tattoopro' ),
				'param_name' => 'inline_style',
				'description' => __( 'Additional inline CSS style', 'tattoopro' ),
				'value' => '',
			),

			array(
				'type' => 'textfield',
				'admin_label' => true,
				'class' => '',
				'heading' => __( 'Extra class', 'tattoopro' ),
				'param_name' => 'class',
				'description' => __( 'Optional additional CSS class to add to the element', 'tattoopro' ),
				'value' => '',
			),
		)
	)
);